# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [8]:
l = np.random.random(50)*50
np.savetxt("simple_data.txt", l)
print(l)

[ 0.94547266 24.11659009 35.94488652 12.31659078 29.50659841 42.80807778
 45.71803695 11.73066154 42.56189891 14.08764796 45.33503115 40.76409965
  0.49181986 40.89745893 23.75365348 30.08287506  9.62338936 23.96609629
 33.33245638 13.44433901 24.59299913 32.24365671 45.21239238  0.04755622
 33.95164332 37.68879519 47.48813082  1.6052427  21.01278771 38.53001213
 10.50415028 43.20243515 17.0850439  29.06713547 38.58671678  4.05977158
 45.93625218  4.3147057  34.75394427  3.25391207 10.5513293  19.27658145
 23.94084619  6.07336109 10.52356057 12.94845829 14.71483392 21.53837158
 25.80633858 35.35479193]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [11]:
m = np.random.randint(-10, 11, (10,10))
np.savetxt("data.txt", m)
print(m)

[[-10  10  -7   7  10   5  -9  -1   3   5]
 [-10   3   6  -1   4 -10   5   9   1   3]
 [  2   9   1  -2  -8  -4  -3  -9  -6   5]
 [  6   5  -1  -5  -6  -6  -5   0   8  -7]
 [  1   1  -1  -5   9   1   0  -4  -6   6]
 [ -5  -1   0   6 -10  -1   9   4   1  10]
 [  1  -4  -7  -2  10   9   1  -2   9   9]
 [ -8   5  -5   7  -9   4   0   3   0   6]
 [  4  -3  -4  -4  -8  -1  -9  -9  10   3]
 [  9   1  -3  10   3   5  -3  10 -10 -10]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [29]:
with open("data.txt", "r") as matrix, open("data.csv", "w") as data_csv:
    data_csv.write("/n".join(",".join(line.split()) for line in matrix))


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.