# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [5]:
d = np.random.random(size = (10))
print(d)
np.savetxt('simple_data.txt', d)

[0.49914127 0.02208275 0.05749285 0.36933585 0.3347733  0.09843094
 0.02934934 0.71043211 0.83614111 0.37043418]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [10]:
r = np.random.random(size = (5,5))
print(r)
np.savetxt('data.txt', r)

[[0.40950303 0.53899545 0.54022662 0.22304917 0.84089774]
 [0.22448238 0.34356225 0.12291324 0.58553156 0.54482156]
 [0.26176532 0.0770346  0.37240478 0.83814896 0.79009332]
 [0.30836119 0.94009625 0.43113851 0.55980801 0.0117788 ]
 [0.35772474 0.73538866 0.308092   0.55193316 0.03574346]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [11]:
t = open('data.txt').read()
csvt = t.replace(' ', ',')
open('data.csv', 'w').write(csvt)

625

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [14]:
ndata = []
with open('credit_card.dat') as f:
    data = ''.join(f.read().splitlines())

    
for r in range(0, len(data)-4, 6):
    binchar = data[r:r+6]
    n = int(binchar,2)
    char = str(n)
    ndata.append(char)
    
result = ''.join(ndata)
with open('number_card.txt', 'w') as f:
    f.write(result)

!cat number_card.dat

--*0661 3063 3742 3150+
"

<<:5774 8528 2087 1117+#
<
6456 1737 4126 6726+"##
.=
-
1684 2253 7570 7118+
8=
<>
,(-,
,
8142 4055 1776 0026+##*

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.